version: '3'
services:

  rabbitMQ:
   image: rabbitmq:3-management
   container_name: 'rabbitmq_container'
   environment:
    - RABBITMQ_DEFAULT_USER=guest
    - RABBITMQ_DEFAULT_PASS=guest
   ports:
    - "5672:5672"
    - "15672:15672"
   expose:
    - 5672
   networks: 
    - fitnesscentarnet2023
   volumes:
    - rabbitmq_data:/var/lib/rabbitmq

  fitnesscentar_sql:
    container_name: app_db
    image: mcr.microsoft.com/mssql/server:2019-latest
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Enaa!2001
      - MSSQL_PID=Developer
    ports:
      - 1405:1433
    expose:
      - 1433
    networks:
      - fitnesscentarnet2023

  fitnesscentar_api:
    restart: unless-stopped
    build:
      context: .
    environment:
      - ConnectionStrings:DefaultConnection=Server=fitnesscentar_sql,1433;Database=IB200005RS2;User=sa;Password=Enaa!2001;ConnectRetryCount=0;TrustServerCertificate=True
      - ASPNETCORE_ENVIRONMENT=Development
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=guest
      - RABBITMQ_PASSWORD=guest 
    ports:
      - 5266:80
    networks:
      - fitnesscentarnet2023
    links:
      - fitnesscentar_sql
    depends_on:
      - fitnesscentar_sql
      - rabbitMQ

  rabbitmq-consumer:
    restart: unless-stopped
    build:
      context: ./RabbitMQConsumer
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=guest
      - RABBITMQ_PASSWORD=guest
      - SMTP_SERVER=smtp.gmail.com
      - SMTP_PORT=587
      - SMTP_USERNAME=fitnesscentar25@gmail.com
      - SMTP_PASSWORD=bqfiomzqoyeyjnvu
    depends_on:
      - fitnesscentar_sql
      - fitnesscentar_api
      - rabbitMQ
    networks:
      - fitnesscentarnet2023
volumes:
  rabbitmq_data:
networks:
  fitnesscentarnet2023:
    driver: bridge

