version: '3'
services:
  rabbitMQ:
   image: rabbitmq:3-management
   container_name: 'rabbitmq_container'
   environment:
    - RABBITMQ_DEFAULT_USER=guest
    - RABBITMQ_DEFAULT_PASS=guest
   ports:
    - 8050:15672
    - 5672:5672
   expose:
    - 5672
   networks: 
    - fitnesscentarnet2023

  fitnesscentar_sql:
    container_name: app_db
    image: mcr.microsoft.com/mssql/server:2019-latest
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Enaa!2001
      - MSSQL_PID=Developer
    ports:
      - 1405:1433
    expose:
      - 1433
    networks:
      - fitnesscentarnet2023

  fitnesscentar_api:
    restart: unless-stopped
    build:
      context: ./FitnessCentar
    environment:
      - ConnectionStrings:DefaultConnection=Server=fitnesscentar_sql,1433;Database=IB200005RS2;User=sa;Password=Enaa!2001;ConnectRetryCount=0;TrustServerCertificate=True
      - ASPNETCORE_ENVIRONMENT=Development
      - RABBITMQ_HOST=rabbitMQ
      - RABBITMQ_USERNAME=guest
      - RABBITMQ_PASSWORD=guest
      - RABBITMQ_VIRTUALHOST=/
    ports:
      - 5266:80
    networks:
      - fitnesscentarnet2023
    links:
      - fitnesscentar_sql
    depends_on:
      - fitnesscentar_sql
      - rabbitMQ


  #auxiliary:
  #  restart: unless-stopped
  #  build:
  #    context: ./Auxiliary
  #  environment:
  #    - ASPNETCORE_ENVIRONMENT=Development
  #    - RABBITMQ_HOST=rabbitMQ
  #    - RABBITMQ_USERNAME=guest
  #    - RABBITMQ_PASSWORD=guest
  #    - RABBITMQ_VIRTUALHOST=/
  #  ports:
  #    - 7138:7138
  #  networks:
  #    - fitnesscentarnet2023
  #  depends_on:
  #    - rabbitMQ
      
    
    
  
networks:
  fitnesscentarnet2023:
    driver: bridge